# ===============================
# For NuImages
# ===============================

# active learning step size of 4k; total batch size of 32 (with 16 per gpu)
faster_rcnn_nuimages_4k_32:
    num_steps: 5
    batch_size: 16
    lr: 0.04
    num_workers: 4

# active learning step size of 4k; total batch size of 32 (with 8 per gpu)
yolox_nuimages_4k_32:
    num_steps: 5
    batch_size: 8
    lr: 0.005
    num_workers: 4
